replicas: 1

rbac:
  create: true

sources:
- ingress

provider: cloudflare

cloudflare:
  apiKey: ""
  email: ""
  proxied: false #override with annotation external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

# N.B. Setting domain filter and txt-owner-id here sets it in the args
# this is not overridden by the environment variables as expected
# so we leave it unset here and patch the env vars in the cluster's kustomize
# @afirth 2019-08
#domainFilter: ""


## Filter sources managed by external-dns via annotation using label selector semantics (optional)
annotationFilter: ""

logLevel: debug
logFormat: json
## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only)
##
## TXT Registry Identifier
# use a kustomize patch and the env_vars
#cluster name
# txtOwnerId: "must-override-external-dns" #with env: EXTERNAL_DNS_TXT_OWNER_ID = cluster-name
policy: sync

## Kubernetes Security Context
## https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m
## Prometheus Exporter / Metrics
##
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
