---
# Source: external-dns/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-cloudflare
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-3.2.0
    app.kubernetes.io/instance: external-dns-cloudflare
    app.kubernetes.io/managed-by: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-cloudflare
subjects:
  - kind: ServiceAccount
    name: external-dns-cloudflare
    namespace: external-dns-cloudflare
