---
# Source: external-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: external-dns-cloudflare
  labels: 
    app.kubernetes.io/name: external-dns
    helm.sh/chart: external-dns-3.2.0
    app.kubernetes.io/instance: external-dns-cloudflare
    app.kubernetes.io/managed-by: Tiller
spec:
  ports:
    - name: http
      port: 7979
      protocol: TCP
      targetPort: http
  selector: 
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/instance: external-dns-cloudflare
  type: ClusterIP
