.SHELLFLAGS := -eu -o pipefail -c
MAKEFLAGS += \
--warn-undefined-variables
SHELL = /bin/bash
.SUFFIXES:

# fetches and templates charts from helm v2 stable repo
# ln -s Makefile ../<chart-name>/Makefile
# @afirth 2019-08

chart ?= $(shell cat chart_name)
name ?= $(notdir $(CURDIR))
repo ?= bitnami
repo_url := https://charts.bitnami.com/bitnami

.PHONY: all
all: clean generate
	@printf "\nINFO: you may want to update the chart first!\n  make fetch\n"

.PHONY: generate
generate:
	helm template ./generated/charts/$(chart) \
		--name $(name) \
		--namespace $(name) \
		--values helm-values.yaml \
		--output-dir ./generated/
	true > generated/kustomization.yaml
	cd generated && kustomize edit add resource $(chart)/templates/*.yaml
	echo "#WARNING This file is generated by make, DO NOT EDIT" >> generated/kustomization.yaml

.PHONY: repo-add
repo-add:
	helm repo add $(repo) $(repo_url)

.PHONY: fetch
fetch:
	-rm -r generated/charts/$(chart)
	helm repo update
	helm fetch $(repo)/$(chart) --untardir generated/charts --untar

.PHONY: clean
clean:
	-rm -r generated/$(chart)/ generated/kustomization.yaml
